[build]
  publish = "dist"
  command = "npm run build"

# Domain redirects for canonical URL
[[redirects]]
  from = "https://www.alt.run/*"
  to = "https://alt.run/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://alt.run/*"
  to = "https://alt.run/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.alt.run/*"
  to = "https://alt.run/:splat"
  status = 301
  force = true

# Specific redirect for running plans with dynamic IDs
[[redirects]]
  from = "/running-plans/plan/*"
  to = "/index.html"
  status = 200

# Redirect all other routes to index.html for SPA client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PDF headers removed - will be added back when PDF is manually created
# [[headers]]
#   for = "/alt-run-beginner-guide.pdf"
#   [headers.values]
#     Content-Type = "application/pdf"
#     Content-Disposition = "inline; filename=alt-run-beginner-guide.pdf"
