// src/pages/TermsPage.jsx
import { Helmet } from 'react-helmet-async';
import { useEffect } from 'react';
import './LegalPages.css';

function TermsPage() {
  // Set the background image for the terms page
  useEffect(() => {
    const pageBackground = document.querySelector('.page-background');
    if (pageBackground) {
      pageBackground.style.backgroundImage = 'url(/images/running-plan.jpg)';
    }

    // Scroll to top when page loads
    window.scrollTo(0, 0);
  }, []);

  // SEO data
  const seoData = {
    title: "Terms and Conditions | Alt.Run",
    description: "Terms and conditions for using Alt.Run and its running plan generator service.",
    canonical: "https://alt.run/terms-and-conditions",
    openGraph: {
      url: "https://alt.run/terms-and-conditions",
      title: "Terms and Conditions | Alt.Run",
      description: "Terms and conditions for using Alt.Run and its running plan generator service.",
      site_name: "Alt.Run"
    }
  };

  return (
    <div className="terms-page">
      <Helmet>
        <title>{seoData.title}</title>
        <meta name="description" content={seoData.description} />
        <link rel="canonical" href={seoData.canonical} />
        <meta property="og:url" content={seoData.openGraph.url} />
        <meta property="og:title" content={seoData.openGraph.title} />
        <meta property="og:description" content={seoData.openGraph.description} />
        <meta property="og:site_name" content={seoData.openGraph.site_name} />
      </Helmet>

      <div className="terms-container">
        <h1>Terms and Conditions for Alt.Run</h1>
        <p>Last Updated: {new Date().toLocaleDateString()}</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using the Alt.Run website and its Running Plan Generator (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this Service.</p>

        <h2>2. Description of Service</h2>
        <p>Alt.Run provides a freemium running plan generator that creates personalized training schedules based on user-inputted data. The basic service is provided free of charge. Premium features may be offered in the future under different terms.</p>

        <h2>3. User Responsibilities</h2>
        <p>You are responsible for providing accurate information (age, training history, goals, etc.) for the plan generator. The generated plans are for informational and general guidance purposes only.</p>
        <p><strong>Important Health Disclaimer:</strong> The training plans generated by Alt.Run are not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or before starting any new exercise program. Never disregard professional medical advice or delay in seeking it because of something you have read or a plan you have received from this Service.</p>

        <h2>4. Intellectual Property</h2>
        <p>The Service and its original content (excluding user-provided data), features, and functionality are and will remain the exclusive property of Alt.Run and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Alt.Run.</p>

        <h2>5. User Data and Privacy</h2>
        <p>Our collection and use of personal information in connection with your access to and use of the Service is described in our <a href="/privacy-policy">Privacy Policy</a>.</p>

        <h2>6. Limitation of Liability</h2>
        <p>In no event shall Alt.Run, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>
        <p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>

        <h2>7. Modification of Terms</h2>
        <p>Alt.Run reserves the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
        <p>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.</p>

        <h2>8. Governing Law</h2>
        <p>These Terms shall be governed and construed in accordance with the laws of California, United States, without regard to its conflict of law provisions.</p>

        <h2>9. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us at alt.run.official@proton.me.</p>
      </div>
    </div>
  );
}

export default TermsPage;

